swagger: "2.0"
info:
  version: "v1"
  title: Please login first

host: booxi.free.beeceptor.com

paths:

  /ApiKey/PartnerKey:
    post:
      summary: Logs in
      parameters:
        - name: ApiKey
          required: true
          in: path
          type: string
        - name: PartnerKey
          required: true
          in: path
          type: string
      responses:
        200:
          description: Login was successful
